services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/service_measure?schema=public
    env_file:
      - .env
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - node_modules
            - dist
        - action: rebuild
          path: package.json

    depends_on:
      - db
    networks:
      - service_measure

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=service_measure
    ports:
      - 5432:5432
    networks:
      - service_measure

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: postgres_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80
    depends_on:
      - db
    networks:
      - service_measure

networks:
  service_measure:
    driver: bridge
